---
- name: Install docker prereqs
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop: "{{ docker_prereqs_packages }}"

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install docker
  apt:
    name: "{{ item }}"
  loop: "{{ docker_packages }}"

- name: Ensure docker cgroup are systemd
  blockinfile:
    path: /etc/docker/daemon.json
    create: yes
    marker: ""
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restart Docker Service
  ansible.builtin.systemd:
    name: docker.service
    state: restarted
    daemon_reload: yes